using PhotoTrail.Windows;
static class XmpChecks
{
 public static async Task RunAsync(ExifToolClient client,string fixtures,string output)
 {
  var folder=Path.Combine(output,"xmp-exchange-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);var count=0;
  void Check(bool value){if(!value)throw new Exception("XMP assertion failed");count++;}
  async Task Reject(Func<Task> action){try{await action();throw new Exception("Unsafe XMP action accepted");}catch(Exception e) when(e is IOException or ArgumentException or System.Xml.XmlException or InvalidDataException){count++;}}
  var photo=await PhotoDocument.LoadAsync(client,Path.Combine(fixtures,"aligned.jpg"));var raw=await client.RunBytesAsync(["-b","-XMP","--",photo.FilePath]);var exported=Path.Combine(folder,"原始导出.xmp");await MetadataXmp.ExportAsync(client,photo,exported);Check(File.ReadAllBytes(exported).SequenceEqual(raw));
  var unchanged=await PhotoDocument.HashAsync(exported);await Reject(()=>MetadataXmp.ExportAsync(client,photo,exported));Check(await PhotoDocument.HashAsync(exported)==unchanged);
  photo.SetDraft(new Dictionary<string,string>{{"XMP-dc:Title","中文,标题\n第二行"},{"XMP-dc:Creator","作者甲\n作者乙"},{"XMP-iptcCore:CountryCode","CHN"}});var edited=Path.Combine(folder,"草稿导出.xmp");await MetadataXmp.ExportAsync(client,photo,edited);var read=await PhotoDocument.LoadAsync(client,edited);foreach(var field in photo.Draft)Check(read.Value(field.Key)==field.Value);Check(await PhotoDocument.HashAsync(photo.FilePath)==photo.SourceHash);
  var imported=await MetadataXmp.ImportAsync(client,edited);Check(imported.Changes["XMP-dc:Creator"]=="作者甲\n作者乙");Check(imported.Changes["XMP-dc:Title"]=="中文,标题\n第二行");Check(!imported.Changes.ContainsKey("XMP-exif:GPSLatitude"));
  var noXmp=await PhotoDocument.LoadAsync(client,Path.Combine(fixtures,"missing.jpg"));noXmp.SetDraft(new Dictionary<string,string>{{"XMP-dc:Title","无XMP起点"}});var created=Path.Combine(folder,"新建.xmp");await MetadataXmp.ExportAsync(client,noXmp,created);Check((await PhotoDocument.LoadAsync(client,created)).Value("XMP-dc:Title")=="无XMP起点");
  var pairedFile=Path.Combine(folder,"paired.jpg");File.Copy(photo.FilePath,pairedFile);var pairedSidecar=Path.ChangeExtension(pairedFile,".xmp");File.Copy(Path.Combine(fixtures,"sidecar.xmp"),pairedSidecar);var paired=await PhotoDocument.LoadAsync(client,pairedFile);var pairedExport=Path.Combine(folder,"旁车导出.xmp");await MetadataXmp.ExportAsync(client,paired,pairedExport);Check((await PhotoDocument.LoadAsync(client,pairedExport)).Value("XMP-dc:Creator")==paired.Value("XMP-dc:Creator"));
  var utf16=Path.Combine(folder,"utf16.xmp");File.WriteAllText(utf16,"<?xml version=\"1.0\" encoding=\"utf-16\"?><x:xmpmeta xmlns:x=\"adobe:ns:meta/\"><rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"><rdf:Description rdf:about=\"\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"><dc:creator><rdf:Seq><rdf:li>UTF16作者</rdf:li></rdf:Seq></dc:creator></rdf:Description></rdf:RDF></x:xmpmeta>",System.Text.Encoding.Unicode);var utfDoc=await PhotoDocument.LoadAsync(client,utf16);var utfExport=Path.Combine(folder,"utf16-export.xmp");await MetadataXmp.ExportAsync(client,utfDoc,utfExport);Check(File.ReadAllBytes(utf16).SequenceEqual(File.ReadAllBytes(utfExport)));Check((await MetadataXmp.ImportAsync(client,utf16)).Changes["XMP-dc:Creator"]=="UTF16作者");
  var opaque=Path.Combine(folder,"opaque.xmp");File.WriteAllText(opaque,"<x:xmpmeta xmlns:x=\"adobe:ns:meta/\"><rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"><rdf:Description rdf:about=\"\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:custom=\"urn:phototrail:test:custom\"><dc:title><rdf:Alt><rdf:li xml:lang=\"fr\">titre conservé</rdf:li></rdf:Alt></dc:title><custom:Opaque>自定义&amp;不丢失</custom:Opaque></rdf:Description></rdf:RDF></x:xmpmeta>");var opaqueDoc=await PhotoDocument.LoadAsync(client,opaque);opaqueDoc.SetDraft(new Dictionary<string,string>{{"XMP-dc:Title","新的默认标题"}});var opaqueOut=Path.Combine(folder,"opaque-export.xmp");await MetadataXmp.ExportAsync(client,opaqueDoc,opaqueOut);
  var xml=System.Xml.Linq.XDocument.Load(opaqueOut);Check(xml.Descendants(System.Xml.Linq.XName.Get("Opaque","urn:phototrail:test:custom")).Single().Value=="自定义&不丢失");Check(xml.Descendants().Any(node=>node.Attribute(System.Xml.Linq.XNamespace.Xml+"lang")?.Value=="fr"&&node.Value=="titre conservé"));Check((await PhotoDocument.LoadAsync(client,opaqueOut)).Value("XMP-dc:Title")=="新的默认标题");
  foreach(var text in new[]{"not xml","<!DOCTYPE x [<!ENTITY remote SYSTEM 'file:///missing'>]><x>&remote;</x>",new string('a',MetadataXmp.MaximumBytes+1)}){var bad=Path.Combine(folder,"bad.xmp");File.WriteAllText(bad,text);await Reject(async()=>{await MetadataXmp.ImportAsync(client,bad);});}
  var cancelled=new CancellationTokenSource();cancelled.Cancel();await Reject(async()=>{await MetadataXmp.ExportAsync(client,photo,Path.Combine(folder,"bad.txt"));});try{await MetadataXmp.ExportAsync(client,photo,Path.Combine(folder,"cancelled.xmp"),cancelled.Token);throw new Exception("Cancellation ignored");}catch(OperationCanceledException){Check(!File.Exists(Path.Combine(folder,"cancelled.xmp")));}
  Check(Directory.GetDirectories(folder,".phototrail-xmp-*").Length==0);Console.WriteLine($"{count} XMP packet/field exchange assertions passed: {folder}");
 }
}
